# Generated by Django 3.0.5 on 2020-12-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('tags', models.CharField(default='', max_length=70)),
                ('advices', models.CharField(max_length=500)),
                ('open_for_f', models.CharField(max_length=7)),
                ('open_for_t', models.CharField(max_length=7)),
                ('quarantine', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Atraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
        ),
    ]
