# Generated by Django 3.0.5 on 2020-12-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraction',
            name='text',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='country',
            name='advices',
            field=models.CharField(max_length=1500),
        ),
    ]
