# Generated by Django 3.0.5 on 2020-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201205_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraction',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
