# Generated by Django 3.0.5 on 2020-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201205_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='advices',
            field=models.CharField(max_length=4000),
        ),
    ]
