# Generated by Django 3.0.5 on 2020-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraction',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
