# Generated by Django 3.0.5 on 2020-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201205_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
